project_id = "kbbrehnyqpulbxyesril"

[functions.google-ai-gateway]
verify_jwt = false

[functions.prime-chat]
verify_jwt = false

[functions.generate-image-gemini]
verify_jwt = false

[functions.prime-speak]
verify_jwt = false

[functions.get-demo-data]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.generate-video-gemini]
verify_jwt = false

[functions.prime-generate-unlockables]
verify_jwt = false

[functions.admin-reset-password]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false
