import JSZip from 'jszip';
import { toast } from 'sonner';

export interface CampaignAssets {
  visuals: {
    hero?: string;
    socialBanner?: string;
    adCreative?: string;
  };
  copy: {
    hero?: { headline: string; subheadline: string; cta: string };
    taglines?: string[];
    emailWelcome?: string;
    emailPromo?: string;
  };
  social: {
    instagram?: string[];
    twitter?: string[];
    tiktok?: string[];
    linkedin?: string[];
  };
  ads: {
    google?: AdVariant[];
    facebook?: AdVariant[];
    tiktok?: AdVariant[];
    instagram?: AdVariant[];
  };
}

export interface AdVariant {
  headline: string;
  description: string;
  cta: string;
  focus?: string;
}

export interface CampaignBrief {
  name: string;
  campaignType: 'launch' | 'feature' | 'seasonal' | 'awareness' | 'promotional';
  targetAudience: 'artists' | 'engineers' | 'both' | 'fans';
  tone: 'hype' | 'professional' | 'authentic' | 'aspirational' | 'edgy';
  keyMessage: string;
}

export const useMarketingExport = () => {
  const exportLaunchKit = async (brief: CampaignBrief, assets: CampaignAssets) => {
    try {
      const zip = new JSZip();
      const campaignSlug = brief.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');

      // Campaign Brief
      zip.file('campaign-brief.json', JSON.stringify({
        name: brief.name,
        type: brief.campaignType,
        audience: brief.targetAudience,
        tone: brief.tone,
        keyMessage: brief.keyMessage,
        generatedAt: new Date().toISOString()
      }, null, 2));

      // Copy folder
      const copyFolder = zip.folder('copy');
      if (assets.copy.hero) {
        copyFolder?.file('hero.json', JSON.stringify(assets.copy.hero, null, 2));
      }
      if (assets.copy.taglines?.length) {
        copyFolder?.file('taglines.json', JSON.stringify(assets.copy.taglines, null, 2));
      }
      if (assets.copy.emailWelcome) {
        copyFolder?.file('email-welcome.txt', assets.copy.emailWelcome);
      }
      if (assets.copy.emailPromo) {
        copyFolder?.file('email-promo.txt', assets.copy.emailPromo);
      }

      // Social folder
      const socialFolder = zip.folder('social');
      if (assets.social.instagram?.length) {
        socialFolder?.file('instagram.json', JSON.stringify(assets.social.instagram, null, 2));
      }
      if (assets.social.twitter?.length) {
        socialFolder?.file('twitter.json', JSON.stringify(assets.social.twitter, null, 2));
      }
      if (assets.social.tiktok?.length) {
        socialFolder?.file('tiktok.json', JSON.stringify(assets.social.tiktok, null, 2));
      }
      if (assets.social.linkedin?.length) {
        socialFolder?.file('linkedin.json', JSON.stringify(assets.social.linkedin, null, 2));
      }

      // Ads folder
      const adsFolder = zip.folder('ads');
      if (assets.ads.google?.length) {
        adsFolder?.file('google-ads.json', JSON.stringify(assets.ads.google, null, 2));
      }
      if (assets.ads.facebook?.length) {
        adsFolder?.file('facebook-ads.json', JSON.stringify(assets.ads.facebook, null, 2));
      }
      if (assets.ads.tiktok?.length) {
        adsFolder?.file('tiktok-ads.json', JSON.stringify(assets.ads.tiktok, null, 2));
      }
      if (assets.ads.instagram?.length) {
        adsFolder?.file('instagram-ads.json', JSON.stringify(assets.ads.instagram, null, 2));
      }

      // README
      zip.file('README.md', `# ${brief.name} - Marketing Launch Kit

Generated by MixxTech Marketing Command Center on ${new Date().toLocaleDateString()}

## Campaign Details
- **Type:** ${brief.campaignType}
- **Target Audience:** ${brief.targetAudience}
- **Tone:** ${brief.tone}
- **Key Message:** ${brief.keyMessage}

## Contents

### /copy
- hero.json - Hero section copy (headline, subheadline, CTA)
- taglines.json - Campaign tagline variations
- email-welcome.txt - Welcome email template
- email-promo.txt - Promotional email template

### /social
- instagram.json - Instagram post variations
- twitter.json - Twitter/X post variations
- tiktok.json - TikTok caption variations
- linkedin.json - LinkedIn post variations

### /ads
- google-ads.json - Google Ads variants
- facebook-ads.json - Facebook/Meta ad variants
- tiktok-ads.json - TikTok ad variants
- instagram-ads.json - Instagram ad variants

## Usage
1. Review each file and customize as needed
2. Copy content directly into your marketing platforms
3. A/B test variants to optimize performance

---
Powered by MixxTech • mixxclub.lovable.app
`);

      // Generate and download
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${campaignSlug}-launch-kit.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast.success('Launch Kit exported successfully!');
    } catch (error) {
      console.error('Export error:', error);
      toast.error('Failed to export Launch Kit');
    }
  };

  return { exportLaunchKit };
};
