/**
 * PressKitExporter — Generate and download a press kit.
 * 
 * Renders a formatted press kit preview and allows downloading
 * as a text file. Includes bio, stats, links, and social info.
 */

import React, { useCallback } from 'react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Download, FileText, Copy, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';
import type { PressKitData } from './types';

interface PressKitExporterProps {
    data: PressKitData;
    accent?: string;
    className?: string;
}

function generatePressKitText(data: PressKitData): string {
    const lines: string[] = [
        '═══════════════════════════════════════════',
        `  ${data.artistName} — ELECTRONIC PRESS KIT`,
        '═══════════════════════════════════════════',
        '',
        `Role: ${data.role || 'Artist'}`,
        `Location: ${data.location || 'Worldwide'}`,
        '',
        '── BIO ──',
        data.tagline || '',
        '',
        data.bio || 'No bio provided.',
        '',
        '── STATS ──',
        `Followers: ${data.stats.followers.toLocaleString()}`,
        `Following: ${data.stats.following.toLocaleString()}`,
        `Profile Views: ${data.stats.profileViews.toLocaleString()}`,
        `Level: ${data.stats.level} (${data.stats.totalXp.toLocaleString()} XP)`,
        '',
    ];

    // Social links
    const socialEntries = Object.entries(data.socialLinks).filter(([, v]) => v);
    if (socialEntries.length > 0) {
        lines.push('── SOCIAL ──');
        socialEntries.forEach(([platform, url]) => {
            lines.push(`${platform}: ${url}`);
        });
        lines.push('');
    }

    // Links
    if (data.links.length > 0) {
        lines.push('── LINKS ──');
        data.links.forEach((link) => {
            lines.push(`${link.title}: ${link.url}`);
        });
        lines.push('');
    }

    lines.push('── CONTACT ──');
    lines.push(`Profile: https://mixxclub.com/u/${data.artistName.toLowerCase().replace(/\s+/g, '')}`);
    lines.push('');
    lines.push('Generated by MixxClub — mixxclub.com');

    return lines.join('\n');
}

export const PressKitExporter: React.FC<PressKitExporterProps> = ({
    data,
    accent = '#f97316',
    className,
}) => {
    const [copied, setCopied] = React.useState(false);

    const pressKitText = generatePressKitText(data);

    const handleDownload = useCallback(() => {
        const blob = new Blob([pressKitText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${data.artistName.replace(/\s+/g, '_')}_PressKit.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast.success('Press kit downloaded!');
    }, [pressKitText, data.artistName]);

    const handleCopy = useCallback(async () => {
        await navigator.clipboard.writeText(pressKitText);
        setCopied(true);
        toast.success('Press kit copied to clipboard!');
        setTimeout(() => setCopied(false), 2000);
    }, [pressKitText]);

    return (
        <div className={cn('space-y-4', className)}>
            {/* Preview card */}
            <div className="relative rounded-xl bg-white/[0.03] border border-white/8 overflow-hidden">
                {/* Header with accent */}
                <div
                    className="h-2"
                    style={{ background: `linear-gradient(to right, ${accent}, ${accent}80)` }}
                />

                <div className="p-5 space-y-4">
                    {/* Artist header */}
                    <div className="flex items-center gap-4">
                        {data.avatarUrl ? (
                            <img src={data.avatarUrl} alt="" className="w-14 h-14 rounded-full object-cover border-2 border-white/10" />
                        ) : (
                            <div className="w-14 h-14 rounded-full bg-primary/20 flex items-center justify-center text-xl">
                                🎵
                            </div>
                        )}
                        <div>
                            <h3 className="font-bold text-foreground">{data.artistName}</h3>
                            <p className="text-sm text-muted-foreground">{data.role} · {data.location}</p>
                        </div>
                    </div>

                    {/* Tagline */}
                    {data.tagline && (
                        <p className="text-sm text-foreground/80 italic">"{data.tagline}"</p>
                    )}

                    {/* Stats row */}
                    <div className="flex gap-4">
                        {[
                            { label: 'Followers', value: data.stats.followers },
                            { label: 'Views', value: data.stats.profileViews },
                            { label: 'Level', value: data.stats.level },
                        ].map((stat) => (
                            <div key={stat.label} className="text-center">
                                <p className="font-bold text-foreground">{stat.value.toLocaleString()}</p>
                                <p className="text-[10px] text-muted-foreground">{stat.label}</p>
                            </div>
                        ))}
                    </div>

                    {/* Bio preview */}
                    <div className="text-xs text-muted-foreground line-clamp-3">
                        {data.bio || 'No bio provided.'}
                    </div>
                </div>
            </div>

            {/* Actions */}
            <div className="flex gap-2">
                <Button onClick={handleDownload} className="flex-1 gap-2" size="sm">
                    <Download className="h-3.5 w-3.5" />
                    Download Press Kit
                </Button>
                <Button
                    variant="outline"
                    onClick={handleCopy}
                    size="sm"
                    className="gap-2 border-white/10"
                >
                    {copied ? (
                        <CheckCircle className="h-3.5 w-3.5 text-green-400" />
                    ) : (
                        <Copy className="h-3.5 w-3.5" />
                    )}
                    {copied ? 'Copied!' : 'Copy'}
                </Button>
            </div>

            <p className="text-[10px] text-muted-foreground text-center">
                <FileText className="h-3 w-3 inline mr-1" />
                Downloads as plain text · PDF export coming soon
            </p>
        </div>
    );
};
